build: move from yarn to pnpm

diff --git a/www/Dockerfile b/www/Dockerfile
--- a/www/Dockerfile
+++ b/www/Dockerfile
@@ -10,11 +10,11 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY --link package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 
 # Rebuild the source code only when needed
@@ -29,7 +29,7 @@ COPY --link  . .
 ENV NEXT_TELEMETRY_DISABLED 1
 
 # If using npm comment out above and use below instead
-RUN yarn build
+RUN pnpm build
 # RUN npm run build
 
 # Production image, copy all the files and run next
@@ -41,8 +41,8 @@ ENV NODE_ENV production
 # ENV NEXT_TELEMETRY_DISABLED 1
 
 RUN \
-  addgroup --system --gid 1001 nodejs; \
-  adduser --system --uid 1001 nextjs
+    addgroup --system --gid 1001 nodejs; \
+    adduser --system --uid 1001 nextjs
 
 COPY --from=builder --link /app/public ./public
 
